CREATE TABLE public.new_raw_input
(
  id serial PRIMARY KEY,
  strona TEXT,
  informacje_dodatkowe TEXT,
  nr_oferty_w_biurze_nieruchomosci TEXT,
  nr_oferty_na_stronie TEXT,
  pietro TEXT,
  dzielnica TEXT,
  opis_finalny TEXT,
  kategoria TEXT,
  liczba_pieter numeric(5),
  wspolrzedne_lon numeric(20,16),
  wspolrzedne_lat numeric(20,16),
  okna TEXT,
  rodzaj_zabudowy TEXT,
  material_budynku TEXT,
  czynsz numeric(12,4),
  rynek TEXT,
  rok_budowy numeric(9,1),
  forma_wlasnosci TEXT,
  stan_wykonczenia TEXT,
  ogrzewanie TEXT,
  dostepne_od TEXT,
  tytul TEXT,
  data_aktualizacji TEXT,
  cena_za_metr numeric(8,2),
  zdjecia_1 TEXT,
  zdjecia_2 TEXT,
  zdjecia_3 TEXT,
  zdjecia_4 TEXT,
  zdjecia_5 TEXT,
  powierzchnia numeric(12,2),
  cena numeric(11,2),
  pokoje TEXT,
  liczba_wyswietlen INTEGER,
  nr_oferty_w_otodom TEXT,
  data_dodania TEXT,
  wspolrzedne TEXT
  
  
)